language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - phpenv config-add travisphpconfig.ini
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/codecept run --verbose