language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit --verbose