<?php //[STAMP] c88699fc37e32dd5c36bac6ed2d0a76c

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile


use Codeception\Module\Asserts;
use Codeception\Module\UnitHelper;

/**
 * Inherited Methods
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void execute($callable)
 * @method void haveFriend($name)
 * @method void comment($description)
 * @method void expect($prediction)
 * @method void lookForwardTo($achieveValue)
 * @method void expectTo($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
*/
class UnitTester extends \Codeception\Actor
{
   
}
